spring:
  thymeleaf:
    cache: false
  # db h2
  h2:
    console:
      enabled: true # console 사용 여부
      path: /h2-console # h2 console path
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    path match:
      matching-strategy: ant_path_matcher

api:
  id: 90NaqIpDfd9MKHwWpwMI
  pw: cluz_oS884
logging:
  level:
    root: debug
